require_relative 'lib/twigg-cache/cache/version'
import File.expand_path('../common.rake', __dir__)

version = Twigg::Cache::VERSION
gem = "twigg-cache-#{version}.gem"
file gem do
  system 'gem build twigg-cache.gemspec'
end

desc "build twigg-cache gem (#{gem})"
task build: gem

desc "push twigg-cache gem (#{gem}) to RubyGems"
task push: [gem] + RELEASE_PREREQS do
  prompt "Push #{gem} to RubyGems"
  system "gem push #{gem}"
end

tag = "twigg-cache/v#{version}"
desc "tag twigg-cache release (#{tag})"
task tag: RELEASE_PREREQS do
  system 'git log -1'
  puts
  message = "#{version} release"
  prompt "Tag current HEAD (shown above) with #{tag} (#{message})"
  system! "git tag #{tag} -m '#{message}'"

  puts
  system 'git remote show -n origin'
  puts
  prompt "Push tags to origin (shown above)"
  system! 'git push origin --tags'
end
