source 'https://rubygems.org'

gemspec

group :development do
  base = File.join(File.dirname(__FILE__), '..')

  gem 'mysql2'
  gem 'twigg-app',    path: File.join(base, 'twigg-app')
  gem 'twigg-gerrit', path: File.join(base, 'twigg-gerrit')
end
