require_relative 'lib/twigg/version'
import File.expand_path('../common.rake', __dir__)

version = Twigg::VERSION
gem = "twigg-#{version}.gem"
file gem do
  system 'gem build twigg.gemspec'
end

desc "build twigg gem (#{gem})"
task build: gem

desc "push twigg gem (#{gem}) to RubyGems"
task push: [gem] + RELEASE_PREREQS do
  prompt "Push #{gem} to RubyGems"
  system "gem push #{gem}"
end

tag = "twigg/v#{version}"
desc "tag twigg release (#{tag})"
task tag: RELEASE_PREREQS do
  system 'git log -1'
  puts
  message = "#{version} release"
  prompt "Tag current HEAD (shown above) with #{tag} (#{message})"
  system! "git tag #{tag} -m '#{message}'"

  puts
  system 'git remote show -n origin'
  puts
  prompt "Push tags to origin (shown above)"
  system! 'git push origin --tags'
end
